### ISSUE TITLE
order Create

### ISSUE THREAD

**Issue by shayank** [mardtendebakker/nsk#204]
###Tasks

- [x] /order create api
- [x] sku auto generate option
- [x] order number auto generate option
